language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: ChangingLegacyCode.xcodeproj
xcode_scheme: ChangingLegacyCode

before_install: rvm use $RVM_RUBY_VERSION

script: 
    - open -b com.apple.iphonesimulator
    - xcodebuild -project ChangingLegacyCode.xcodeproj -scheme ChangingLegacyCode -sdk iphonesimulator build test
    - slather
    - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml
