language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator
xcode_project: ChangingLegacyCode.xcodeproj
xcode_scheme: ChangingLegacyCode

install: bundle install --without=documentation

before_script: 
    - open -b com.apple.iphonesimulator

script:
    - xcodebuild -project ChangingLegacyCode.xcodeproj -scheme ChangingLegacyCode -sdk iphonesimulator build test
    
after_success:
    - slather
    - bash <(curl -s https://codecov.io/bash) -f cobertura.xml
