language: objective-c
osx_image: xcode7.3

before_script: 
    - open -b com.apple.iphonesimulator

script:
    - xcodebuild -project ChangingLegacyCode.xcodeproj -scheme ChangingLegacyCode -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test
    
after_success:
    - slather
    - bash <(curl -s https://codecov.io/bash) -f cobertura.xml
