language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: ChangingLegacyCode.xcodeproj
xcode_scheme: ChangingLegacyCode
script: "xcodebuild -project ChangingLegacyCode.xcodeproj -scheme ChangingLegacyCode -sdk iphonesimulator build test"
